version: "3.0"
services:
  frontend:
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile

